export const CREATE_STORY_REQUEST = "CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAILURE = "CREATE_STORY_FAILURE";

export const GET_STORY_REQUEST = "GET_STORY_REQUEST";
export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const GET_STORY_FAILURE = "GET_STORY_FAILURE";

export const DELETE_STORY_REQUEST = "DELETE_STORY_REQUEST";
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";
export const DELETE_STORY_FAILURE = "DELETE_STORY_FAILURE";

export const GET_STORIES_REQUEST = "GET_STORIES_REQUEST";
export const GET_STORIES_FAILURE = "GET_STORIES_FAILURE";
export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";