export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const GET_HISTORY_MESSAGE_REQUEST = "GET_HISTORY_MESSAGE_REQUEST";
export const GET_HISTORY_MESSAGE_SUCCESS = "GET_HISTORY_MESSAGE_SUCCESS";
export const GET_HISTORY_MESSAGE_FAILURE = "GET_HISTORY_MESSAGE_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";


